spring:
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: update
      connection:
        provider_disables_autocommit: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      database: postgres
      database-platform: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
springdoc:
  swagger-ui:
    operationsSorter: alpha
    tagsSorter: alpha